//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class demo_tushar
    {
        public int id { get; set; }
        public string message_1 { get; set; }
        public string message_2 { get; set; }
        public string message_3 { get; set; }
    }
}
